xml.etree.CElementTree deprecated
Any activity fails to build with Python 3.9;

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from sugar3.activity import bundlebuilder
  File "sugar3/activity/bundlebuilder.py", line 44, in <module>
    import xml.etree.cElementTree as ET
ModuleNotFoundError: No module named 'xml.etree.cElementTree'

See https://docs.python.org/3.9/whatsnew/3.9.html#removed
"The xml.etree.cElementTree module has been removed."

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1817644

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>
Signed-off-by: James Cameron <quozl@laptop.org>