Fix AttributeError on drop to ColorToolButton
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sugar3/graphics/colorbutton.py", line 246, in __drag_data_get_cb
    selection_data.set(selection_data.target, 16, data)
AttributeError: 'SelectionData' object has no attribute 'target'

Reproducer; open the brush properties, try to drag a predefined colour
button into the toolbar button above the brush properties label.

aa8a5e70 ("Port from Python 2 to six") was probably incomplete, in
that porting to Python 3 did not adjust for the changes in GTK, or
changes in GTK had happened independently.

Fixes https://github.com/sugarlabs/paint-activity/issues/43

Thanks to Akshay-krish for finding the cause.

Signed-off-by: James Cameron <quozl@laptop.org>