use xml.etree.ElementTree as xml.etree.CElementTree will be deprecated
sugar-paint fails to build for fedora with Python 3.9.0a5 and throws this error

Traceback (most recent call last):
  File "/builddir/build/BUILD/Paint-70/./setup.py", line 19, in <module>
    from sugar3.activity import bundlebuilder
  File "/usr/lib/python3.9/site-packages/sugar3/activity/bundlebuilder.py", line 44, in <module>
    import xml.etree.cElementTree as ET
ModuleNotFoundError: No module named 'xml.etree.cElementTree'

Python 3.9 will be included in Fedora 33.

See https://docs.python.org/3.9/whatsnew/3.9.html#removed
"The xml.etree.cElementTree module has been removed."

See https://bugs.python.org/issue36543

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>